name: build

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🤌🏽
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: |
          docker-compose -f docker-compose.prod.yml build
          echo "List of docker images"
          docker images
          echo "OK"
          docker tag htm-test_htm-web ghcr.io/artmarydotir/htm-test-web:latest
          docker tag htm-test_htm-backend ghcr.io/artmarydotir/htm-test-backend:latest
          docker push ghcr.io/artmarydotir/htm-test-web:latest
          docker push ghcr.io/artmarydotir/htm-test-backend:latest
