# Copyright(c) 2021 aasaam software development group
FROM node:16-bullseye-slim AS frontend

RUN export DEBIAN_FRONTEND=noninteractive ; \
  export LANG=en_US.utf8 ; \
  export LC_ALL=C.UTF-8 ; \
  apt-get update -y \
  && apt-get autoremove -y \
  && apt-get -y upgrade && apt-get install -y --no-install-recommends curl build-essential ca-certificates \
  && curl -sf https://gobinaries.com/tj/node-prune | sh \
  && echo 'cache = "/tmp/npm"' > /root/.npmrc \
  && npm -g update \
  && node-prune /usr/local/lib/node_modules \
  && mkdir /app \
  && rm -r /var/lib/apt/lists/* && rm -rf /tmp && mkdir /tmp && chmod 777 /tmp && truncate -s 0 /var/log/*.log

ADD app/frontend /app/frontend

RUN cd /app/frontend \
  && npm install --force \
  && npm run make

FROM nginx:1

COPY --from=frontend app/frontend/dist /web-app
ADD nginx/nginx.conf /etc/nginx/nginx.conf
ADD nginx/mime.types /etc/nginx/mime.types
ADD nginx/common-server.conf /etc/nginx/common-server.conf
ADD nginx/common-proxy.conf /etc/nginx/common-proxy.conf
ADD nginx/templates/default.prod.conf.template /etc/nginx/templates/default.conf.template
