const {
  // graphql-scalars
  BigIntResolver,
  ByteResolver,
  CurrencyResolver,
  DateResolver,
  DateTimeResolver,
  DurationResolver,
  EmailAddressResolver,
  GUIDResolver,
  HexColorCodeResolver,
  HSLAResolver,
  HSLResolver,
  IPv4Resolver,
  IPv6Resolver,
  ISBNResolver,
  JSONObjectResolver,
  JSONResolver,
  LocalDateResolver,
  LocalEndTimeResolver,
  LocalTimeResolver,
  LongResolver,
  MACResolver,
  NegativeFloatResolver,
  NegativeIntResolver,
  NonEmptyStringResolver,
  NonNegativeFloatResolver,
  NonNegativeIntResolver,
  NonPositiveFloatResolver,
  NonPositiveIntResolver,
  ObjectIDResolver,
  PhoneNumberResolver,
  PortResolver,
  PositiveFloatResolver,
  PositiveIntResolver,
  PostalCodeResolver,
  RGBAResolver,
  RGBResolver,
  SafeIntResolver,
  TimeResolver,
  UnsignedFloatResolver,
  UnsignedIntResolver,
  URLResolver,
  USCurrencyResolver,
  UtcOffsetResolver,
  UUIDResolver,
  VoidResolver,
} = require('graphql-scalars');

const Query = require('./Query');
const Mutation = require('./Mutation');
// const OtherResolvers = require('./Resolvers');

module.exports = {
  // graphql-scalars
  BigInt: BigIntResolver,
  Byte: ByteResolver,
  Currency: CurrencyResolver,
  Date: DateResolver,
  DateTime: DateTimeResolver,
  Duration: DurationResolver,
  EmailAddress: EmailAddressResolver,
  GUID: GUIDResolver,
  HexColorCode: HexColorCodeResolver,
  HSL: HSLResolver,
  HSLA: HSLAResolver,
  IPv4: IPv4Resolver,
  IPv6: IPv6Resolver,
  ISBN: ISBNResolver,
  JSON: JSONResolver,
  JSONObject: JSONObjectResolver,
  LocalDate: LocalDateResolver,
  LocalEndTime: LocalEndTimeResolver,
  LocalTime: LocalTimeResolver,
  Long: LongResolver,
  MAC: MACResolver,
  NegativeFloat: NegativeFloatResolver,
  NegativeInt: NegativeIntResolver,
  NonEmptyString: NonEmptyStringResolver,
  NonNegativeFloat: NonNegativeFloatResolver,
  NonNegativeInt: NonNegativeIntResolver,
  NonPositiveFloat: NonPositiveFloatResolver,
  NonPositiveInt: NonPositiveIntResolver,
  ObjectID: ObjectIDResolver,
  PhoneNumber: PhoneNumberResolver,
  Port: PortResolver,
  PositiveFloat: PositiveFloatResolver,
  PositiveInt: PositiveIntResolver,
  PostalCode: PostalCodeResolver,
  RGB: RGBResolver,
  RGBA: RGBAResolver,
  SafeInt: SafeIntResolver,
  Time: TimeResolver,
  UnsignedFloat: UnsignedFloatResolver,
  UnsignedInt: UnsignedIntResolver,
  URL: URLResolver,
  USCurrency: USCurrencyResolver,
  UtcOffset: UtcOffsetResolver,
  UUID: UUIDResolver,
  Void: VoidResolver,

  // custom
  Query,
  Mutation,
  // OtherResolvers,
  // Project: {
  //   members: async (root, args, { container }) => {
  //     console.log(root);
  //     console.log(args);
  //     // const { ProjectListRepository } = container;
  //     // return ProjectListRepository.findAllUserByProjectId(id);
  //     // console.log(context.event);
  //   },
  //   // data: async (parent, args, context) => parent,
  // },
};
